### ISSUE TITLE
AttributeError: 'Profile' object has no attribute 'get'

### ISSUE THREAD

**Issue by limitingfactor** [jordan-wright/rapportive#4]
Hey, I'm new to Python so this might be an error on my part, but after installing your python scripts and running the test command:

rapportive_cmd -e jmwright798@gmail.com

I get:

``` bash
Traceback (most recent call last):
  File "/usr/local/bin/rapportive_cmd", line 5, in <module>
    pkg_resources.run_script('rapportive==0.1.0', 'rapportive_cmd')
  File "build/bdist.macosx-10.9-x86_64/egg/pkg_resources.py", line 492, in run_script
  File "build/bdist.macosx-10.9-x86_64/egg/pkg_resources.py", line 1350, in run_script
  File "/usr/local/lib/python2.7/site-packages/rapportive-0.1.0-py2.7.egg/EGG-INFO/scripts/rapportive_cmd", line 8, in <module>
    exit(main())
  File "/usr/local/Cellar/python/2.7.5/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/rapportive-0.1.0-py2.7.egg/rapportive/rapportive.py", line 135, in main
    ___process_email(arg, output)
  File "/usr/local/Cellar/python/2.7.5/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/rapportive-0.1.0-py2.7.egg/rapportive/rapportive.py", line 105, in ___process_email
    success = profile.get('success')
AttributeError: 'Profile' object has no attribute 'get'
```

**Comment by jordan-wright** [comment]
Great catch - I think I fixed it. We just changed the way the script works, which is likely the reason why the bug slipped past. Let me know if you run into any other problems!

**Comment by limitingfactor** [comment]
Wow, I don't think I've ever had github issue fixed that fast. Thanks, everything is working now!
