### ISSUE TITLE
profile.success raises AttributeError

### ISSUE THREAD

**Issue by MichalZaniewicz** [jordan-wright/rapportive#8]
Traceback (most recent call last):
  File "/usr/local/bin/rapportive_cmd", line 5, in 
    pkg_resources.run_script('rapportive==0.1.0', 'rapportive_cmd')
  File "/usr/lib/python2.6/dist-packages/pkg_resources.py", line 467, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.6/dist-packages/pkg_resources.py", line 1200, in run_script
    execfile(script_filename, namespace, namespace)
  File "/usr/local/lib/python2.6/dist-packages/rapportive-0.1.0-py2.6.egg/EGG-INFO/scripts/rapportive_cmd", line 8, in 
    exit(main())
  File "/usr/local/lib/python2.6/dist-packages/rapportive-0.1.0-py2.6.egg/rapportive/rapportive.py", line 132, in main
    ___process_email(arg, output)
  File "/usr/local/lib/python2.6/dist-packages/rapportive-0.1.0-py2.6.egg/rapportive/rapportive.py", line 104, in ___process_email
    if profile and profile.success != 'nothing_useful':
AttributeError: 'unicode' object has no attribute 'success'

class Profile line 41, should be initialized with all those fields set to empty strings in case person is not given and then, after line 103, you could use smth like: if profile and isinstance(profile, Profile) and profile.success:

**Comment by jordan-wright** [comment]
Thanks for the heads up! I'm afraid I don't have any time this week to take care of this. If it can wait a week or two, I'll definitely get to it.

Otherwise, feel free to send a pull request! I'd be happy to merge if everything looks good.

I'll keep this issue open until this gets taken care of.

**Comment by max-arnold** [comment]
Got the same error. In my case the actual value in `profile` variable is the string `too many requests`.
